#! /bin/sh
#
# Generate output from dbd2csv and compare to expected output
#
# Mar-2012, Pat Welch, pat@mousebrains.com
#

CMD=../bin/dbd2csv
TMP=../tmp

if [ ! -x "$CMD" ] ; then
  echo "$CMD is not executable"
  exit 1
fi

if ! diff --version >/dev/null ; then
  echo No diff command found
  exit 1
fi

if ! mkdir -p "$TMP" ; then
  echo "Unable to create $TMP"
  exit 1
fi

doCompare() {
  tmpfn=$TMP/dbdcsv.out.$$
  ref=$1
  shift

  if [ ! -e "$ref" ] ; then
    echo "Reference file $ref does not exist"
    exit 1
  fi

  for file in "$@" ; do
    if [ ! -e "$file" ] ; then
      echo "Dinkum Binary Data file $file does not exist"
      exit 1
    fi
  done

  if ! "$CMD" -o "$tmpfn" "$@" ; then
    echo "Failed to execute $CMD on $*"
    rm -f "$tmpfn"
    exit 1
  fi

  if ! diff -q "$tmpfn" "$ref" ; then
    echo "Failed on comparison of $* sensors"
    diff "$tmpfn" "$ref"
    rm -f "$tmpfn"
    exit 1
  fi

  rm -f "$tmpfn"
}

doCompare test.sbd.csv test.sbd
doCompare test.tbd.csv test.tbd
doCompare test.both.csv test.sbd test.tbd

exit 0
