.TH dbd2netCDF "February 2012" "Version 1.0" "USER COMMANDS"
.SH NAME
dbd2netCDF \- translate 
.I "Dinkum Binary Data"
 files into a 
.I netCDF
file
.SH SYNOPSIS
.B dbd2netCDF 
.B [\-hsVv]
.B "[\-c filename]"
.B "[\-C directory]" 
.B "[\-k filename]" 
.B "[\-m mission]"
.B "[\-M mission]"
.B "[\-o filename]"
dbdFiles...
.SH DESCRIPTION
Read in a set of 
.I "Dinkum Binary Data"
files, and translate them into
a 
.I netCDF 
file.
.SH OPTIONS
.TP
.B "\-c filename "
A comma, space, tab, and/or newline deliminated file containing names of sensors to
select rows on. If any sensor specified by the file is set or updated in a row,
the row is output into the 
.I netCDF
file.
.TP
.B "\-C directory"
Directory to use for cached sensor lists.

For each 
.I "Dinkum Binary Data"
file that contains a sensor list, 
if the filename derived from the 
.B sensor_list_crc 
record in the header records
does not exist in the
.B directory,
then create a sensor list file.

For each 
.I "Dinkum Binary Data"
file that does not contain a sensor list, and
whose sensor list has not been seen already, look in the
.B directory
for an appropriate sensor list file.

.B "If the directory does not exist, it is created world writeable!"
.TP
.B \-h 
display a short help message
.TP
.B "\-k filename"
A comma, space, tab, and/or newline deliminated file containing names of sensors to
output into the 
.I netCDF
file.
.TP 
.B "\-m mission"
For each 
.I "Dinkum Binary Data"
file, if the header record
.B mission_name
is mission, skip processing this file.

This option may be repeated multiple times.
.TP 
.B "\-M mission"
For each 
.I "Dinkum Binary Data"
file, if the header record
.B mission_name
is mission, process this file.

This option may be repeated multiple times.
.TP
.B "\-o filename"
Filename of generated 
.I netCDF
output file.

.B "The \-o option is required."
.TP
.B \-s
Skip the first data record in each 
.I "Dinkum Binary Data"
file, except for the first file.
.TP
.B \-V
Print out software version.
.TP
.B \-v
Enable output of some diagnostic information.
.SH EXAMPLES
.TP
.B
dbd2netCDF -o foobar.nc *.dbd
.PP
Read in all the files ending in .dbd, and output 
.I netCDF
file, foobar.nc
.SH EXIT STATUS
A non-zero return code indicates an unrecoverable error occurred.
A zero return code indicates success.
.SH NOTES
The generated 
.I netCDF
file has two dimensions:
.TP
i
row index of data
.TP
j
file index for each dbd file

Each sensor is stored as a variable indexed by 
.B i.

The sensor units are attached to each variable as an attribute.

Each dbd file's header information is recorded in a set of variables prefixed
by 
.B hdr_ 
and indexed by 
.B i
.

Use
.B ncdump -h foobar.nc
to see the variables' names contained in the 
.I netCDF
file foobar.nc.
.SH NOTES
This was  designed to translate the
.I "Dinkum Binary Data"
files generated by 
.B "Webb Research's SLOCUM"
gliders.

All glider generated Dinkum Binary Data files are translated in their entirety, except for the
.B .dbd
files. These are split into three files,
one for all sensors beginning in m_ or c_, 
another for all sensors beginning in sci_, and
another for all other sensors.

There are two reason for the split, one is the access time of the variables in the
.I netCDF
files.
The other is to deal with the separation of the science and flight data into 
.B .dbd
and
.B .ebd
files.

.SH AUTHOR
Pat Welch (pat (at) mousebrains.com)
.SH SEE ALSO
dbdSensors(1)
dbd2csv(1)
ncdump(1)

.SH COPYRIGHT NOTICE
Copyright (C) 2012 Pat Welch
Licenced under GPLV3.

Permission is granted to make and distribute verbatim copies of this manual 
provided the copyright notice and this permission notice are preserved on all copies.

Permission is granted to copy and distribute  modified  versions  of  this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under  the  terms  of  a  permission
notice identical to this one.

Permission  is  granted to copy and distribute translations of this manual
into another language, under the above conditions for  modified  versions,
except that this permission notice may be stated in a translation approved
by the Free Software Foundation.


